version: '3'
services:
  front-end:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - back-end
  back-end:
    build:
      context: ./backend
    ports:
      - "5000:5000"
